create table if not exists public.favorite_exercise (
    id integer generated by default as identity primary key,
    user_id integer not null references public."user"(id) on delete cascade,
    exercise varchar(100) not null,
    constraint uq_favorite_exercise_user_exercise unique (user_id, exercise)
);

alter table public.favorite_exercise enable row level security;
